# Generated by Django 6.0.3 on 2026-03-06 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_shipping_status'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('shipped', 'Enviado'), ('delivered', 'Entregado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant'),
        ),
    ]
