# nginx/nginx.docker.conf
# Strangler Pattern para entorno Docker Compose

upstream django_backend  { server django_app:8000; }
upstream flask_payment   { server flask_payment:5000; }
upstream flask_inventory { server ms_inventory:5001; }
upstream flask_cart      { server ms_cart:5002; }
upstream flask_customers { server ms_customers:5003; }
upstream flask_shipping  { server ms_shipping:5004; }

server {
    listen 80;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Health de Nginx
    location /nginx-health {
        return 200 '{"status":"ok","service":"nginx"}';
        add_header Content-Type application/json;
    }

    # ── Microservicios v2 ──────────────────────────────────────

    location /api/v2/checkout/ {
        proxy_pass         http://flask_payment;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    location /api/v2/products/ {
        proxy_pass         http://flask_inventory;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    location /api/v2/inventory/ {
        proxy_pass         http://flask_inventory;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    location /api/v2/cart/ {
        proxy_pass         http://flask_cart;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    location /api/v2/customers/ {
        proxy_pass         http://flask_customers;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    location /api/v2/shipping/ {
        proxy_pass         http://flask_shipping;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    # ── Monolito Django legacy (todo lo demás) ─────────────────

    location / {
        proxy_pass         http://django_backend;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 60s;
    }
}