# nginx/nginx.docker.conf
# Strangler Pattern para entorno Docker Compose

upstream django_backend {
    server django_app:8000;
}

upstream flask_backend {
    server flask_payment:5000;
}

server {
    listen 80;
    server_name _;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Microservicio nuevo estrangulado
    location /api/v2/ {
        proxy_pass         http://flask_backend;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 30s;
    }

    # Monolito legacy
    location / {
        proxy_pass         http://django_backend;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_redirect     off;
        proxy_read_timeout 60s;
    }
}
